; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = PAMI_Firmware
description = PAMI Firmware
default_envs = PAMI_USB_NO_WIFI

[common]
monitor_speed = 921600
upload_speed = 921600
upload_protocol = espota
upload_port = 192.168.137.101
upload_flags = -p 3232

[env]
platform = espressif32
board = ESP32-S3-Tiny
framework = arduino
build_type = debug
build_src_filter = 
	+<*>
	-<.git/>
	-<.svn/>
	-<test-simulator/>
	-<**/*.jpeg>
	-<**/*.txt>
	-<*.jpeg>
	-<*.txt>
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}
monitor_filters =
	colorize
	time
	send_on_enter
	esp32_exception_decoder
monitor_echo = yes
monitor_eol = LF
lib_deps = 
; on utilise la version 3.9.16 de FastLED car la 3.9.17 est bugguée: error: 'LookaheadMode' has not been declared
	waspinator/AccelStepper@^1.64
	;adafruit/Adafruit NeoPixel@^1.12.3
	fastled/FastLED@3.9.16
	robotis-git/Dynamixel2Arduino@^0.8.0
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit INA219@^1.2.3
	stm32duino/STM32duino VL53L8CX @ ^2.0.3

[env:PAMI_WOKWI]
upload_protocol = esptool
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=c++17
	-std=gnu++17
	-D ARDUINO_ESP32S3_DEV
	-D ARDUINO_USB_MODE=1
	-D NO_WIFI
	-D SIMULATOR
	-D WOKWI

[env:PAMI_USB_NO_WIFI]
upload_protocol = esptool
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=c++17
	-std=gnu++17
	-D ARDUINO_ESP32S3_DEV
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D NO_WIFI

[env:PAMI_USB_WITH_WIFI]
upload_protocol = esptool
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=c++17
	-std=gnu++17
	-D ARDUINO_ESP32S3_DEV
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D WITH_WIFI
